### ISSUE TITLE
Release tag is incorrect for kubectl

### ISSUE THREAD

**Issue by samip5** [rancher/kubectl#5]
The repository's release is tagged incorrectly as   it's not v1.22.x,  but rather v1.21.3.

**Comment by dweomer** [comment]
@samip5 apologies but I do not quite follow. This project exists as a `FROM scratch` packaging of `kubectl` that is necessary to minimally support the optional cordon and drain functionality for upgrade jobs applied by https://github.com/rancher/system-upgrade-controller. I try to keep it up-to-date-ish but there are some missing tags here as far as upstream k8s releases are concerned.

Is there a tag that we are missing that you care to see where the nearest available version does not suffice?

**Comment by samip5** [comment]
Yes, the point is that if I were to pull rancher/kubectl:v1.21.3, I would want that specific version kubectl, and same could be said for v1.21.4.

My use case is cronjob that needs to use kubectl for certificate reflection to other namespaces, like this: <https://github.com/samip5/k8s-cluster/blob/main/cluster/apps/networking/secret-reflector/cronjob.yaml>

**Comment by superseb** [comment]
Let us know if this still needs a follow up, we are close to start creating containers for the latest versions and from then on, automatically for the new versions
